bot_name = 'LAKMÉ'
weather = 'rainy'



responses = {
    '(.*)your(.*)name(.*)':['myname is {0}'.format(bot_name),
                           'they call me {0}'.format(bot_name),
                           '{0} is my name'.format(bot_name)],
    '(.*)born(.*)':['i was created on 20/02/2020','i m 1 day old',
                    'my owner knows it'],
    '(.*)how(.*)are(.*)you':['thanks for asking,i am fine',
                             'i am a bot,i dont have feelings'],
    '(.*)what(.*)are(.*)you(.*)doing':['i\'m dreaming about winning the mini project expo',
                                       'i\'m answering your questions',
                                       'i dont really know'],
    '(.*)fees(.*)':['to know the details about the fee structure,contact our college using any of the following\n*email:sece@sece.ac.in\n*phone:04259 200300\n*mobile:09715317171\n*fax:04259 200305'],
    '(.*)fee(.*)':['to know the details about the fee structure,contact our college using any of the following\n*email:sece@sece.ac.in\n*phone:04259 200300\n*mobile:09715317171\n*fax:04259 200305'],
    '(.*)sports(.*)':['sports facilities available in sece:\nVolleyball Court,\nBall Badminton Court,\nHandball Court,\nBasket Ball Court,\nCricket Nets (Concrete and Turf Wicket),\nTable Tennis,\nCarrom,\nChess,\nGym (separate for boys and girls),\nFootball'],
    '(.*)sport(.*)':['sports facilities available in sece:\nVolleyball Court,\nBall Badminton Court,\nHandball Court,\nBasket Ball Court,\nCricket Nets (Concrete and Turf Wicket),\nTable Tennis,\nCarrom,\nChess,\nGym (separate for boys and girls),\nFootball'],
    '(.*)laboratory(.*)':['ece:\nCommunications Lab,Microwave Lab,Networking Lab,VLSI Lab,DSP Lab,Digital electronics Lab,Linear integrated circuits Lab,Electronic circuit’s Lab,Electronic devices Lab I & II,Micrprocessor Lab,Project Lab,PG simulations Lab\ncse:\nComputer Practice laboratory,DBMS and Networking Laboratory,Case tools and Graphics laboratory,Project Lab,CSE Research Lab,IT Center\neee:\nPower Electronic Laboratory,electrical machines laboratory,electronics laboratory,eee simulations laboratory,measurements and instrumentation laboratory\nmechanical:\nWelding Shop,Sheet Metal Shop,Foundry Shop,Fitting Shop,Fluid Mechanics and Machinery Lab,Lathe Shop,CAD Lab,CAM Lab,Engineering Graphics Lab'],
    '(.*)foreign(.*)language(.*)':['sece has an center for foreign language to make students imbibe communication skills in foreign language,\nthe languages currently available are japanese and german with many more to come'],
    '(.*)campus(.*)language(.*)':['the campus language of sece is english'],
    '(.*)entrepreneurship(.*)':['Entrepreneurship developments cell has been installed to promote entrepreneurship skills in the students and make them become the best entrepreneur'],
    '(.*)entrepreneur(.*)':['Entrepreneurship developments cell has been installed to promote entrepreneurship skills in the students and make them become the best entrepreneur'],
    '(.*)class(.*)room(.*)':['all the classrooms are "smart," with high-speed data networks and lcd projectors for audio and video'],
    '(.*)class(.*)rooms(.*)':['all the classrooms are "smart," with high-speed data networks and lcd projectors for audio and video'],
    '(.*)class(.*)':['all the classrooms are "smart," with high-speed data networks and lcd projectors for audio and video'],
    '(.*)infrastructure(.*)':['sri eshwar college of engineering is located in a tranquil and conducive ambience,\ncreating an ideal learning environment to stimulate intellectual and personal growth.\nthe main campus contain\n*smart class rooms\n*central library\n*it centre\n*amenity centre \n*hostel'],
    '(.*)awards(.*)':['*best industry linked emerging institute award\n*best placement and career building award\n*sustainable institute industry partnership award\n*best industry interface institute award and many more..'],
    '(.*)todays(.*)weather(.*)':['weather is {0}'.format(weather),
                      'today it is {0}'.format(weather),
                      'it\'s {0} right now'.format(weather)],
    '(.*)college(.*)':['our college is an autonomous institution affiliated to anna university',
                       'an autonomous institution with naac accredition'
                       'our college is an autonomous institution with 10 years of educational excellence'],
    '(.*)departments(.*)':['ug:\n* b.e.cse\n* b.e.ece\n* b.e.mech\n* b.e.eee\n* b.e.civil\n* b.e.cce\n* b.e.it\npg:\n* m.e.vlsi design\n* m.e.cse\n* m.e.engineering design'],
    '(.*)department(.*)':['ug:\n* b.e.cse\n* b.e.ece\n* b.e.mech\n* b.e.eee\n* b.e.civil\n* b.e.cce\n* b.e.it\npg:\n* m.e.vlsi design\n* m.e.cse\n* m.e.engineering design'],
    '(.*)cutoff(.*)':['cutoff varies each year,each department has an unique cutoff,the average cutoff is 153.75'],
    '(.*)tnea(.*)code(.*)':['the tnea code of sece is 2739'],
    '(.*)scholarship(.*)':['*185 & above = all free\n*184.75-180 = 75% of tution fee\n*179.75-175 = 50% of tution fee\n*170-160(mbc) = 50% of tution fee'],
    '(.*)hostel(.*)':['hostels available for both boys and girls.All rooms are private in four-occupancy apartments.facilities available for hostel studemts include:\nFood service,\nSolar water heater,\nStudy space,\nLounge,\nManagement office,\nRecreation room,\nComputer Center,\nIndoor games,\nSeparate multistation Gym facilities for boys and girls,\nLaundry facility,\nSafe entry to the building is assured by security desk staffed round-the-clock,\nWifi in Lounge,\nRo Water.'],
    '(.*)accomodation(.*)':['hostels available for both boys and girls.All rooms are private in four-occupancy apartments.facilities available for hostel studemts include:\nFood service,\nSolar water heater,\nStudy space,\nLounge,\nManagement office,\nRecreation room,\nComputer Center,\nIndoor games,\nSeparate multistation Gym facilities for boys and girls,\nLaundry facility,\nSafe entry to the building is assured by security desk staffed round-the-clock,\nWifi in Lounge,\nRo Water'],
    '(.*)facilities(.*)':['*smart class room\n*central library\n*it centre\n*amenity centre\n*hostel\n*play ground\n*gym and others...'],
    '(.*)tie(.*)ups(.*)':['*texas intruments\n*infosys limited\n*virtusa\n*vmware and many more...'],
    '(.*)tie(.*)up(.*)':['*texas intruments\n*infosys limited\n*virtusa\n*vmware and many more...'],
    '(.*)placement(.*)':['sece is securing 95+% placements for the past 10 years'],
    '(.*)placements(.*)':['at sri eshwar,placements get bigger and better year on year with 90+ recruiters recruiting our students with many more to come'],
    '(.*)contact(.*)':['*email:sece@sece.ac.in\n*phone:04259 200300\n*mobile:09715317171\n*fax:04259 200305'],
    '(.*)located(.*)':['sri eshwar college of engineering,kondampatti[post],vadasithur(via),coimbatore-641202'],
    '(.*)address(.*)':['sri eshwar college of engineering,kondampatti[post],vadasithur(via),coimbatore-641202'],
    '(.*)end(.*)':['if you want to end the chat,type exit'],
    '(.*)timing(.*)':['classes starts at 8.40am and ends at 4.10pm'],
    '(.*)events(.*)':['to know about current events,visit www.sece.ac.in'],
    '(.*)library(.*)':['The Central Library is built the area of 466 sq. m 120 Seating capacity and specialized collections of Books, Journals & Non-book materials are available in Engineering and Technology Science and Humanities.\nThe Central Library is replete with 20,545 Volumes of 8,491 Title of Books, 1,970 CDS. 383 Back Volume.\nThe Central Library Subscribes to 89 National and 73 International Journals and provides classroom teaching through NPTEL Facility.'],
    '(.*)libraries(.*)':['The Central Library is built the area of 466 sq. m 120 Seating capacity and specialized collections of Books, Journals & Non-book materials are available in Engineering and Technology Science and Humanities.\nThe Central Library is replete with 20,545 Volumes of 8,491 Title of Books, 1,970 CDS. 383 Back Volume.\nThe Central Library Subscribes to 89 National and 73 International Journals and provides classroom teaching through NPTEL Facility.'],
    '(.*)transport(.*)':['The College is committed to provide students with flexible & cost effective network of transport.\nto know the bus routes and bus numbers visit https://www.sece.ac.in/transports.aspx'],
    '(.*)transportation(.*)':['The College is committed to provide students with flexible & cost effective network of transport.\nto know the bus routes and bus numbers visit https://www.sece.ac.in/transports.aspx'],
    '(.*)lab(.*)':['ece:\nCommunications Lab,Microwave Lab,Networking Lab,VLSI Lab,DSP Lab,Digital electronics Lab,Linear integrated circuits Lab,Electronic circuit’s Lab,Electronic devices Lab I & II,Micrprocessor Lab,Project Lab,PG simulations Lab\ncse:\nComputer Practice laboratory,DBMS and Networking Laboratory,Case tools and Graphics laboratory,Project Lab,CSE Research Lab,IT Center\neee:\nPower Electronic Laboratory,electrical machines laboratory,electronics laboratory,eee simulations laboratory,measurements and instrumentation laboratory\nmechanical:\nWelding Shop,Sheet Metal Shop,Foundry Shop,Fitting Shop,Fluid Mechanics and Machinery Lab,Lathe Shop,CAD Lab,CAM Lab,Engineering Graphics Lab'],
    '(.*)labs(.*)':['ece:\nCommunications Lab,Microwave Lab,Networking Lab,VLSI Lab,DSP Lab,Digital electronics Lab,Linear integrated circuits Lab,Electronic circuit’s Lab,Electronic devices Lab I & II,Micrprocessor Lab,Project Lab,PG simulations Lab\ncse:\nComputer Practice laboratory,DBMS and Networking Laboratory,Case tools and Graphics laboratory,Project Lab,CSE Research Lab,IT Center\neee:\nPower Electronic Laboratory,electrical machines laboratory,electronics laboratory,eee simulations laboratory,measurements and instrumentation laboratory\nmechanical:\nWelding Shop,Sheet Metal Shop,Foundry Shop,Fitting Shop,Fluid Mechanics and Machinery Lab,Lathe Shop,CAD Lab,CAM Lab,Engineering Graphics Lab'],
    '(.*)bus(.*)':['the college is committed to provide students with flexible & cost effective network of transport.to know the bus routes and bus numbers visit https://www.sece.ac.in/transports.aspx'],
    '(.*)club(.*)':['the clubs available in sece are:\n*fine arts club\n*ieee club\n*science club\n*music club\n*quiz club\n*photo and movie club'],
    '(.*)clubs(.*)':['the clubs available in sece are:\n*fine arts club\n*ieee club\n*science club\n*music club\n*quiz club\n*photo and movie club'],
    '(.*)higher(.*)studies(.*)':['higher education cell has been opened for students to make the student realize the prosperities of higher studies and train them in their area of interest.\nin our higher education cell, student\'s interest and potential will be identified by our hec team which is formed by field specialists with the help of our counselors,\naccordingly he/she will be guided with their goals for their higher education,\n*hec members will make the third year students complete their test in ielts or toefl with high score,\nguide them the views and benefits on cat, mat, gate, gmat, and sat'],
    '(.*)higher(.*)education(.*)':['higher education cell has been opened for students to make the student realize the prosperities of higher studies and train them in their area of interest.\nin our higher education cell, student\'s interest and potential will be identified by our hec team which is formed by field specialists with the help of our counselors,\naccordingly he/she will be guided with their goals for their higher education,\n*hec members will make the third year students complete their test in ielts or toefl with high score,\nguide them the views and benefits on cat, mat, gate, gmat, and sat'],
    'default':['I cant hear you.........',
               'can you repeat it once again!!!',
               'pardon???',
               'type exit to Exit']
    }



